# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeodbIO
                                 A QGIS plugin
 Connects to spatial data from geodb.io via api
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-05
        copyright            : (C) 2025 by geodb.io
        email                : admin@geodb.io
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeodbIO class from plugin module.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .plugin import GeodbIO
    return GeodbIO(iface)
